name: Scheduled Bin Check

on:
  schedule:
    # Runs at 17:45 UTC on Sunday and Wednesday
    # This corresponds to:
    # - 5:45 PM UK time (GMT)
    # - 6:45 PM UK time (BST)
    - cron: '45 17 * * SUN,WED'
  workflow_dispatch: # Allows manual triggering

jobs:
  run-bin-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bin checker script
        env:
          MY_POSTCODE: ${{ secrets.MY_POSTCODE }}
          MY_HOUSE_NUMBER: ${{ secrets.MY_HOUSE_NUMBER }}
          BINS_GOOGLE_CALENDAR_ID: ${{ secrets.BINS_GOOGLE_CALENDAR_ID }}
          BINS_GOOGLE_CREDENTIALS_JSON: ${{ secrets.BINS_GOOGLE_CREDENTIALS_JSON }}
        run: python3 -m src.check_bins --upload-google
        
